# 多UAV-USV协同巡检系统默认配置
# 所有配置参数的中央管理

# 系统基础配置
system:
  name: "多UAV-USV协同巡检系统"
  version: "0.1.0"
  random_seed: 42
  log_level: "INFO"
  
# 智能体配置
agents:
  uav:
    count: 3  # UAV数量
    max_speed: 15.0  # m/s
    battery_capacity: 300.0  # Wh
    base_power: 50.0  # W
    task_power: 20.0  # W
    cruise_speed_ratio: 0.7  # 经济巡航速度比例
  
  usv:
    count: 1  # USV数量
    max_speed: 8.0  # m/s
    battery_capacity: 1000.0  # Wh
    base_power: 100.0  # W
    task_power: 30.0  # W
    cruise_speed_ratio: 0.8

# 环境配置
environment:
  map_width: 1024  # 地图宽度（像素）
  map_height: 1024  # 地图高度（像素）
  real_scale: 1000.0  # 真实尺度（米）
  
# 任务配置
tasks:
  max_tasks: 50  # 最大任务数
  priority_range: [0.5, 3.0]  # 优先级范围
  duration_range: [30.0, 300.0]  # 任务持续时间范围（秒）
  energy_range: [5.0, 50.0]  # 能量需求范围（Wh）
  generation_rate: 0.1  # 动态任务生成率（tasks/second）

# HCA-A*路径规划器配置
planner:
  grid_resolution: 20.0  # 网格分辨率（米）
  time_weight: 1.0  # 时间权重
  energy_weight: 1.0  # 能量权重
  safety_margin: 1.2  # 安全系数
  max_iterations: 10000  # 最大搜索迭代次数

# 2-opt优化器配置
optimizer:
  max_iterations: 1000  # 最大优化迭代次数
  improvement_threshold: 0.01  # 改进阈值（1%）
  time_weight: 1.0  # 时间权重
  energy_weight: 1.0  # 能量权重
  random_seed: 42

# 强化学习调度器配置
scheduler:
  # 网络结构
  state_dim: 64  # 状态维度
  action_dim: 100  # 动作维度
  hidden_dims: [256, 256, 128]  # 隐藏层维度
  
  # 训练参数
  learning_rate: 1e-4  # 学习率
  gamma: 0.99  # 折扣因子
  epsilon: 0.1  # 探索概率
  epsilon_min: 0.01  # 最小探索概率
  epsilon_decay: 0.995  # 探索衰减率
  
  # 经验回放
  buffer_size: 10000  # 回放缓冲区大小
  batch_size: 64  # 批次大小
  target_update_freq: 100  # 目标网络更新频率
  
  # 训练设置
  max_episodes: 1000  # 最大训练回合数
  max_steps_per_episode: 200  # 每回合最大步数
  eval_freq: 50  # 评估频率

# 能源感知任务分配器配置
energy_aware_allocator:
  # 成本函数权重
  cost_weights:
    distance: 0.3    # 距离权重
    energy: 0.4      # 能耗权重  
    time: 0.2        # 时间权重
    risk: 0.1        # 风险权重
  
  # 安全参数
  safety_margin: 0.25          # 25%安全余量
  max_tasks_per_uav: 5         # 每个UAV最大任务数
  energy_threshold: 0.15       # 15%电量阈值
  min_energy_reserve: 0.1      # 10%最小预留电量
  
  # 自适应权重调整
  adaptive_weights:
    enable: true               # 启用自适应权重
    adjustment_factor: 0.1     # 调整因子
    load_threshold: 0.8        # 高负载阈值
    energy_crisis_threshold: 0.2  # 能源危机阈值

# USV后勤调度器配置  
usv_logistics:
  # 支援效益权重
  support_benefit_weights:
    task_value: 0.4      # 任务价值权重
    energy_cost: 0.3     # 能源成本权重
    time_cost: 0.2       # 时间成本权重
    distance_cost: 0.1   # 距离成本权重
  
  # 支援参数
  min_reserve_energy_ratio: 0.3    # 30%预留电量比例
  max_support_distance: 5000       # 5km最大支援距离
  charging_transfer_efficiency: 0.85  # 85%充电传输效率
  support_response_time: 300       # 5分钟支援响应时间
  
  # 巡逻参数
  patrol_enabled: true             # 启用巡逻功能
  patrol_radius: 300               # 300像素巡逻半径
  patrol_waypoint_count: 4         # 4个巡逻路径点

# 充电决策器配置
charging_decision:
  # 决策因子权重
  decision_factors:
    distance: 0.3        # 距离因子权重
    queue_time: 0.25     # 排队时间权重
    availability: 0.25   # 可用性权重
    urgency: 0.2         # 紧急度权重
  
  # 预测参数
  queue_prediction_window: 900     # 15分钟预测窗口
  emergency_threshold: 0.1         # 10%紧急电量阈值
  charging_station_capacity: 2     # 充电桩容量
  usv_charging_rate: 50           # USV充电功率(W)

# 动态重调度器配置
dynamic_reallocator:
  # 触发阈值
  trigger_thresholds:
    critical_energy: 0.15           # 15%临界电量
    performance_degradation: 0.2    # 20%性能下降
    load_imbalance: 0.3            # 30%负载不均衡
    task_failure_rate: 0.1         # 10%任务失败率
  
  # 重调度参数
  reallocation_interval: 900       # 15分钟周期性检查
  smooth_transition_steps: 3       # 3步平滑过渡
  max_reallocation_frequency: 4    # 每小时最大重调度次数
  local_adjustment_threshold: 0.3  # 30%智能体影响阈值

# 仿真配置
simulation:
  time_step: 1.0  # 仿真时间步长（秒）
  max_simulation_time: 3600.0  # 最大仿真时间（秒）
  visualization: true  # 是否可视化
  save_trajectory: true  # 是否保存轨迹
  
# 评估指标配置
metrics:
  # 性能指标
  task_completion_rate: true  # 任务完成率
  average_completion_time: true  # 平均完成时间
  energy_efficiency: true  # 能源效率
  path_optimality: true  # 路径最优性
  
  # 系统指标
  load_balance: true  # 负载均衡
  response_time: true  # 响应时间
  throughput: true  # 吞吐量
  
  # 稳定性指标
  success_rate: true  # 成功率
  failure_recovery: true  # 故障恢复

# 输出配置
output:
  results_dir: "results"  # 结果输出目录
  models_dir: "models"  # 模型保存目录
  logs_dir: "logs"  # 日志目录
  plots_dir: "plots"  # 图表目录
  save_frequency: 100  # 保存频率（训练步数）
  
# 硬件配置
hardware:
  use_gpu: true  # 是否使用GPU
  gpu_memory_fraction: 0.8  # GPU内存使用比例
  num_workers: 4  # 并行工作进程数
  
# 调试配置
debug:
  verbose: false  # 详细输出
  profile_performance: false  # 性能分析
  save_intermediate: false  # 保存中间结果
  check_gradients: false  # 梯度检查